blogicum/blog/urls.py
# blogicum/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.index, name="index"),
    path("posts/<int:post_id>/", views.post_detail, name="post_detail"),
    path(
        "category/<slug:slug>/",
        views.category_posts,
        name="category_posts",
    ),
    path("posts/create/", views.PostCreateView.as_view(), name="post_create"),
    path(
        "posts/<int:post_id>/edit/",
        views.PostUpdateView.as_view(),
        name="post_edit",
    ),
    path(
        "posts/<int:post_id>/comment/",
        views.add_comment,
        name="add_comment"
    ),
    path(
        "posts/<int:post_id>/delete/",
        views.PostDeleteView.as_view(),
        name="post_delete",
    ),
]

urlpatterns += [
    path(
        "posts/<int:post_id>/edit_comment/<int:comment_id>/",
        views.CommentUpdateView.as_view(),
        name="edit_comment",
    ),
    path(
        "posts/<int:post_id>/delete_comment/<int:comment_id>/",
        views.CommentDeleteView.as_view(),
        name="delete_comment",
    ),
    path(
        "profile/<str:username>/",
        views.profile_detail,
        name="profile_detail",
    ),
    path(
        "profile/<str:username>/edit/",
        views.edit_profile,
        name="edit_profile",
    ),
]

blogicum/blogicum/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings  # Для медиа-файлов
from django.conf.urls.static import static  # Для медиа-файлов
from django.views.generic import CreateView
from django.urls import reverse_lazy
from blog.forms import CreationForm

urlpatterns = [
    path("admin/", admin.site.urls),
    path("pages/", include("pages.urls", namespace="pages")),
    path("", include("blog.urls", namespace="blog")),
    path("auth/", include("django.contrib.auth.urls")),
    path(
        "auth/registration/register/",
        CreateView.as_view(
            form_class=CreationForm,
            success_url=reverse_lazy("blog:index"),
            template_name="registration/registration_form.html",
        ),
        name="register",
    ),  # Используем CreateView для регистрации
]

# Для отдачи медиа-файлов в режиме разработки
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

handler500 = "blog.views.server_error"

handler404 = "pages.views.page_not_found"
handler403 = "pages.views.csrf_failure"

blogicum/blog/models.py
from django.db import models
from django.contrib.auth import get_user_model

# Получаем встроенную модель User
User = get_user_model()


class Category(models.Model):
    title = models.CharField(
        "Заголовок", max_length=256, help_text="Макс длина — 256 символов."
    )
    description = models.TextField("Описание")
    slug = models.SlugField(
        "Идентификатор",
        unique=True,
        help_text=(
            "Идентификатор страницы для URL; "
            "разрешены символы латиницы, цифры, дефис и подчёркивание."
        ),
    )
    is_published = models.BooleanField(
        "Опубликовано",
        default=True,
        help_text="Снимите галочку, чтобы скрыть публикацию.",
    )
    created_at = models.DateTimeField("Добавлено", auto_now_add=True)

    class Meta:
        verbose_name = "категория"
        verbose_name_plural = "Категории"
        ordering = ["title"]  # Для удобства, можно удалить

    def __str__(self):
        return self.title


class Location(models.Model):
    name = models.CharField(
        "Название места", max_length=256, help_text="256 символов."
    )
    is_published = models.BooleanField(
        "Опубликовано",
        default=True,
        help_text="Снимите галочку, чтобы скрыть публикацию.",
    )
    created_at = models.DateTimeField("Добавлено", auto_now_add=True)

    class Meta:
        verbose_name = "местоположение"
        verbose_name_plural = "Местоположения"
        ordering = ["name"]  # Для удобства, можно удалить

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField("Заголовок", max_length=256)
    text = models.TextField("Текст")
    pub_date = models.DateTimeField(
        verbose_name="Дата и время публикации",
        help_text="Если установить дату и время в будущем — "
        "можно делать отложенные публикации.",
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="posts",
        verbose_name="Автор публикации",
    )
    location = models.ForeignKey(
        Location,
        on_delete=models.SET_NULL,
        null=True,  # Разрешает NULL в базе данных
        blank=True,  # Разрешает не заполнять поле в формах/админке
        related_name="posts",
        verbose_name="Местоположение",
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        null=True,
        blank=False,
        related_name="posts",
        verbose_name="Категория",
    )
    is_published = models.BooleanField(
        "Опубликовано",
        default=True,
        help_text="Снимите галочку, чтобы скрыть публикацию.",
    )
    image = models.ImageField(
        "Изображение",
        upload_to="posts/",  # Директория внутри MEDIA_ROOT
        blank=True,
        null=True,
    )
    created_at = models.DateTimeField("Добавлено", auto_now_add=True)

    class Meta:
        verbose_name = "публикация"
        verbose_name_plural = "Публикации"
        ordering = [
            "-pub_date"
        ]  # По умолчанию сортируем по дате публикации (от новых к старым)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name="comments",
        verbose_name="Публикация",
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="comments",
        verbose_name="Автор комментария",
    )
    text = models.TextField("Текст комментария")
    created_at = models.DateTimeField(
        "Дата и время создания", auto_now_add=True
    )

    class Meta:
        verbose_name = "комментарий"
        verbose_name_plural = "Комментарии"
        ordering = ["created_at"]

    def __str__(self):
        return self.text[:15]  # Первые 15 символов текста комментария

blogicum/blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Post, Comment  # Импортируем для форм

# Импортируем модель пользователя
from django.contrib.auth import get_user_model

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = ("first_name", "last_name", "username", "email")


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            "title",
            "text",
            "pub_date",
            "category",
            "location",
            "image",
            "is_published",
        )


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("text",)


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("first_name", "last_name", "username", "email")

blogicum/blog/views.py
from django.shortcuts import get_object_or_404, render
from django.utils import timezone  # Работа с датой и временем
from django.http import Http404  # Генерация ошибки 404
from .models import Post, Category, Comment  # Импорт моделей
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView  # Для CBV
from django.contrib.auth import get_user_model
from .forms import PostForm, CommentForm, ProfileEditForm  # Импортируем формы
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    UserPassesTestMixin,
)  # Для CBV и проверки прав
from django.shortcuts import redirect  # Для ручных редиреков
from django.db.models import Count, Q
from django.core.paginator import Paginator


User = get_user_model()


def get_published_posts(queryset):
    """Фильтрует посты по статусу публикации и дате."""
    return queryset.filter(
        Q(pub_date__lte=timezone.now()) | Q(pub_date__isnull=True),
        is_published=True,
        category__is_published=True,
    )


def get_posts_with_comments(queryset):
    """Аннотирует queryset постов количеством комментариев и сортирует."""
    return queryset.annotate(
        comment_count=Count("comments")
    ).order_by("-pub_date")


def get_page_obj(request, post_list, posts_per_page=10):
    """Возвращает объект страницы пагинатора."""
    paginator = Paginator(post_list, posts_per_page)
    page_number = request.GET.get("page")
    return paginator.get_page(page_number)


def index(request):
    post_list = get_posts_with_comments(
        get_published_posts(
            Post.objects.select_related(
                "category", "author", "location"
            )
        )
    )
    page_obj = get_page_obj(request, post_list)
    context = {
        "page_obj": page_obj,
    }
    return render(request, "blog/index.html", context)


def category_posts(request, slug):
    category = get_object_or_404(Category, slug=slug, is_published=True)
    post_list = get_posts_with_comments(
        get_published_posts(
            Post.objects.select_related("author", "location").filter(
                category=category
            )
        )
    )
    page_obj = get_page_obj(request, post_list)
    context = {
        "category": category,
        "page_obj": page_obj,
    }
    return render(request, "blog/category.html", context)


def post_detail(request, post_id):
    post = get_object_or_404(
        Post.objects.select_related(
            "category", "author", "location"
        ), pk=post_id
    )

    if request.user != post.author:
        if (
            (post.pub_date is not None and post.pub_date > timezone.now())
            or not post.is_published
            or (post.category is None or not post.category.is_published)
        ):
            raise Http404("Публикация не найдена или не опубликована.")

    comment_form = CommentForm()
    context = {
        "post": post,
        "comment_form": comment_form,
    }
    return render(request, "blog/detail.html", context)


def profile_detail(request, username):
    profile = get_object_or_404(User, username=username)

    if request.user == profile:
        post_list = get_posts_with_comments(
            profile.posts.select_related(
                "category", "location"
            )
        )
    else:
        post_list = get_posts_with_comments(
            get_published_posts(
                profile.posts.select_related("category", "location")
            )
        )

    page_obj = get_page_obj(request, post_list)
    context = {
        "profile": profile,
        "page_obj": page_obj,
    }
    return render(request, "blog/profile.html", context)


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    template_name = "blog/create.html"

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy(
            "blog:profile_detail",
            kwargs={"username": self.request.user.username},
        )


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    form_class = PostForm
    template_name = "blog/create.html"
    pk_url_kwarg = "post_id"

    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author

    def handle_no_permission(self):
        post = self.get_object()
        return redirect("blog:post_detail", post_id=post.pk)

    def get_success_url(self):
        return reverse_lazy(
            "blog:post_detail", kwargs={"post_id": self.get_object().pk}
        )


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
        return redirect("blog:post_detail", post_id=post_id)
    context = {
        "post": post,
        "form": form,
    }
    return render(request, "blog/detail.html", context)


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    template_name = "blog/post_confirm_delete.html"
    pk_url_kwarg = "post_id"

    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author

    def handle_no_permission(self):
        post = self.get_object()
        return redirect("blog:post_detail", post_id=post.pk)

    def get_success_url(self):
        return reverse_lazy(
            "blog:profile_detail",
            kwargs={"username": self.request.user.username},
        )


class CommentDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Comment
    template_name = "blog/comment_confirm_delete.html"
    pk_url_kwarg = "comment_id"

    def get_object(self, _queryset=None):
        post_id = self.kwargs.get("post_id")
        comment_id = self.kwargs.get("comment_id")
        return get_object_or_404(Comment, pk=comment_id, post__pk=post_id)

    def test_func(self):
        comment = self.get_object()
        return self.request.user == comment.author

    def handle_no_permission(self):
        comment = self.get_object()
        return redirect("blog:post_detail", post_id=comment.post.pk)

    def get_success_url(self):
        return reverse_lazy(
            "blog:post_detail", kwargs={"post_id": self.kwargs.get("post_id")}
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if "form" in context:
            del context["form"]
        return context


class CommentUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Comment
    form_class = CommentForm
    template_name = "blog/comment_edit.html"
    pk_url_kwarg = "comment_id"

    def get_object(self, _queryset=None):
        post_id = self.kwargs.get("post_id")
        comment_id = self.kwargs.get("comment_id")
        return get_object_or_404(Comment, pk=comment_id, post__pk=post_id)

    def test_func(self):
        comment = self.get_object()
        return self.request.user == comment.author

    def handle_no_permission(self):
        comment = self.get_object()
        return redirect("blog:post_detail", post_id=comment.post.pk)

    def get_success_url(self):
        comment = self.get_object()
        return reverse_lazy(
            "blog:post_detail", kwargs={"post_id": comment.post.pk}
        )


@login_required
def edit_profile(request, username):
    user_to_edit = get_object_or_404(User, username=username)

    if request.user != user_to_edit:
        return redirect("blog:profile_detail", username=username)

    if request.method == "POST":
        form = ProfileEditForm(request.POST, instance=user_to_edit)
        if form.is_valid():
            form.save()
            return redirect("blog:profile_detail", username=username)
    else:
        form = ProfileEditForm(instance=user_to_edit)

    context = {
        "form": form,
        "profile": user_to_edit,
    }
    return render(request, "blog/edit_profile.html", context)


def server_error(request):
    return render(request, "pages/500.html", status=500)

blogicum/templates/blog/category.html
{% extends "base.html" %}
{% block title %}
  Публикации в категории {{ category.title }}
{% endblock %}
{% block content %}
  <h1 class="text-center">Публикации в категории - {{ category.title }}</h1>
  <p class="col-6 offset-3 mb-5 lead text-center">{{ category.description }}</p>
  {% for post in page_obj %}
    <article class="mb-5">  
      {% include "includes/post_card.html" %}
    </article>   
  {% endfor %}
  {% include "includes/pagination.html" %}
{% endblock %}

blogicum/templates/blog/comment.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}
  {% if '/edit_comment/' in request.path %}
    Редактирование комментария
  {% else %}
    Удаление комментария
  {% endif %}
{% endblock %}
{% block content %}
  {% if user.is_authenticated %}
    <div class="col d-flex justify-content-center">
      <div class="card" style="width: 40rem;">
        <div class="card-header">
          {% if '/edit_comment/' in request.path %}
            Редактирование комментария
          {% else %}
            Удаление комментария
          {% endif %}
        </div>
        <div class="card-body">
          <form method="post"
            {% if '/edit_comment/' in request.path %}
              action="{% url 'blog:edit_comment' comment.post_id comment.id %}"
            {% endif %}>
            {% csrf_token %}
            {% if not '/delete_comment/' in request.path %}
              {% bootstrap_form form %}
            {% else %}
              <p>{{ comment.text }}</p>
            {% endif %}
            {% bootstrap_button button_type="submit" content="Отправить" %}
          </form>
        </div>
      </div>
    </div>
  {% endif %}
{% endblock %}

blogicum/templates/blog/comment_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Удаление комментария{% endblock %}

{% block content %}
    <div class="container">
        <div class="alert alert-danger" role="alert">
            Вы уверены, что хотите удалить этот комментарий?
            <br>
            <small>"{{ object.text }}"</small>
        </div>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Да, удалить</button>
            <a href="{% url 'blog:post_detail' object.post.pk %}" class="btn btn-secondary">Отмена</a>
        </form>
    </div>
{% endblock %}

blogicum/templates/blog/comment_edit.html
{% extends 'base.html' %}

{% block title %}Редактировать комментарий{% endblock %}

{% block content %}
    <div class="container">
        <h1>Редактировать комментарий</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Сохранить</button>
            <a href="{% url 'blog:post_detail' comment.post.pk %}" class="btn btn-secondary">Отмена</a>
        </form>
    </div>
{% endblock %}

blogicum/templates/blog/create.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}
  {% if '/edit/' in request.path %}
    Редактирование публикации
  {% elif "/delete/" in request.path %}
    Удаление публикации
  {% else %}
    Добавление публикации
  {% endif %}
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-header">
        {% if '/edit/' in request.path %}
          Редактирование публикации
        {% elif '/delete/' in request.path %}
          Удаление публикации
        {% else %}
          Добавление публикации
        {% endif %}
      </div>
      <div class="card-body">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {% if not '/delete/' in request.path %}
            {% bootstrap_form form %}
          {% else %}
            <article>
              {% if form.instance.image %}
                <a href="{{ form.instance.image.url }}" target="_blank">
                  <img class="border-3 rounded img-fluid img-thumbnail mb-2" src="{{ form.instance.image.url }}">
                </a>
              {% endif %}
              <p>{{ form.instance.pub_date|date:"d E Y" }} | {% if form.instance.location and form.instance.location.is_published %}{{ form.instance.location.name }}{% else %}Планета Земля{% endif %}<br>
              <h3>{{ form.instance.title }}</h3>
              <p>{{ form.instance.text|linebreaksbr }}</p>
            </article>
          {% endif %}
          {% bootstrap_button button_type="submit" content="Отправить" %}
        </form>
      </div>
    </div>
  </div>
{% endblock %}

blogicum/templates/blog/detail.html
{% extends "base.html" %}
{% block title %}
  {{ post.title }} | {% if post.location and post.location.is_published %}{{ post.location.name }}{% else %}Планета Земля{% endif %} |
  {{ post.pub_date|date:"d E Y" }}
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-body">
        {% if post.image %}
          <a href="{{ post.image.url }}" target="_blank">
            <img class="border-3 rounded img-fluid img-thumbnail mb-2 mx-auto d-block" src="{{ post.image.url }}">
          </a>
        {% endif %}
        <h5 class="card-title">{{ post.title }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">
          <small>
            {% if not post.is_published %}
              <p class="text-danger">Пост снят с публикации админом</p>
            {% elif not post.category.is_published %}
              <p class="text-danger">Выбранная категория снята с публикации админом</p>
            {% endif %}
            {{ post.pub_date|date:"d E Y, H:i" }} | {% if post.location and post.location.is_published %}{{ post.location.name }}{% else %}Планета Земля{% endif %}<br>
            От автора <a class="text-muted" href="{% url 'blog:profile_detail' post.author.username %}">@{{ post.author.username }}</a> в
            категории {% include "includes/category_link.html" %}
          </small>
        </h6>
        <p class="card-text">{{ post.text|linebreaksbr }}</p>
        {% if user == post.author %}
          <div class="mb-2">
            <a class="btn btn-sm text-muted" href="{% url 'blog:post_edit' post.pk %}" role="button">
              Отредактировать публикацию
            </a>
            <a class="btn btn-sm text-muted" href="{% url 'blog:post_delete' post.pk %}" role="button">
              Удалить публикацию
            </a>
          </div>
        {% endif %}
        {% include "includes/comments.html" %}
      </div>
    </div>
  </div>
{% endblock %}

blogicum/templates/blog/edit_profile.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block title %}Редактирование профиля{% endblock %}

{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card">
          <div class="card-header">
            Редактирование профиля пользователя {{ profile.username }}
          </div>
          <div class="card-body">
            <form method="post">
              {% csrf_token %}
              {% bootstrap_form form %}
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">Сохранить</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

blogicum/templates/blog/index.html
{% extends "base.html" %}
{% block title %}
  Лента записей
{% endblock %}
{% block content %}
  {% for post in page_obj %}
    <article class="mb-5">
      {% include "includes/post_card.html" %}
    </article>
  {% endfor %}
  {% include "includes/pagination.html" %}
{% endblock %}

blogicum/templates/blog/post_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Удаление публикации{% endblock %}

{% block content %}
    <div class="container">
        <div class="alert alert-danger" role="alert">
            Вы уверены, что хотите удалить публикацию "{{ object.title }}"?
        </div>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Да, удалить</button>
            <a href="{% url 'blog:post_detail' object.pk %}" class="btn btn-secondary">Отмена</a>
        </form>
    </div>
{% endblock %}

blogicum/templates/blog/profile.html
{% extends "base.html" %}
{% block title %}
  Страница пользователя {{ profile.username }}
{% endblock %}
{% block content %}
  <h1 class="mb-5 text-center ">Страница пользователя {{ profile.username }}</h1>
  <small>
    <ul class="list-group list-group-horizontal justify-content-center mb-3">
      <li class="list-group-item text-muted">Имя пользователя: {% if profile.get_full_name %}{{ profile.get_full_name }}{% else %}не указано{% endif %}</li>
      <li class="list-group-item text-muted">Регистрация: {{ profile.date_joined }}</li>
      <li class="list-group-item text-muted">Роль: {% if profile.is_staff %}Админ{% else %}Пользователь{% endif %}</li>
    </ul>
    <ul class="list-group list-group-horizontal justify-content-center">
      {% if user.is_authenticated and request.user == profile %}
      <a class="btn btn-sm text-muted" href="{% url 'blog:edit_profile' username=profile.username %}">Редактировать профиль</a>
      <a class="btn btn-sm text-muted" href="{% url 'password_change' %}">Изменить пароль</a>
      {% endif %}
    </ul>
  </small>
  <br>
  <h3 class="mb-5 text-center">Публикации пользователя</h3>
  {% for post in page_obj %}
    <article class="mb-5">
      {% include "includes/post_card.html" %}
    </article>
  {% endfor %}
  {% include "includes/pagination.html" %}
{% endblock %}

blogicum/templates/blog/user.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}
  Редактирование профиля
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-header">
        Редактирование профиля - {{ request.user.username }}
      </div>
      <div class="card-body">
        <form method="post">
          {% csrf_token %}
          {% bootstrap_form form %}
          {% bootstrap_button button_type="submit" content="Отправить" %}
        </form>
      </div>
    </div>
  </div>
{% endblock %}